# export EB_CONFIG_FILE=/aws/.elasticbeanstalk/config.yml

branch-defaults:
  default:
    environment: Ecommerce2-env
    group_suffix: null
global:
  application_name: ecommerce2
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
