# Generated by Django 5.0.6 on 2024-06-19 22:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_price_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
    ]
