# Generated by Django 5.0.6 on 2024-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="/images/default.jpg", upload_to="images/"),
        ),
    ]
