# Generated by Django 5.0.6 on 2024-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_remove_product_image_alter_productphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_image",
            field=models.ImageField(default="/images/default.jpg", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
