# Generated by Django 5.0.6 on 2025-01-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images'),
        ),
    ]
