# Generated by Django 5.0.6 on 2025-01-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
