# Generated by Django 5.0.6 on 2024-07-03 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="user",
        ),
    ]
