# Generated by Django 5.0.6 on 2024-07-09 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_remove_orderitem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address2",
            new_name="number",
        ),
    ]
